name: Docker Image CI

#触发器
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

#项目任务
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push
      #导入这个模块来完成自动编译和推送
      uses: docker/build-push-action@v3
      with:
          context: .
          push: true
          #通过QEMU和Buildx来实现多平台编译
          platforms: linux/amd64,linux/arm64,linux/arm
          #指定用户/仓库名
          tags: rehiy/webox:latest
    - name: Docker Hub Description
      #通过md文件生成dockerhub描述
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: rehiy/webox:latest
        readme-filepath: ./README.md
